{{- if not .Values.creds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  accesskey: {{ .Values.secret.accessKey | b64enc }}
  secretkey: {{ .Values.secret.secretKey | b64enc }}
{{- end }}