apiVersion: v2
name: playngo
description: Testing environment for the playandgo application
dependencies:
  # Operators:
  - name: community-operator
    repository: https://mongodb.github.io/helm-charts
    version: 0.8.0
    condition: community-operator.enabled
  - name: rabbitmq-cluster-operator
    repository: https://charts.bitnami.com/bitnami
    version: ~3.5
    condition: rabbitmq-cluster-operator.enabled
  - name: postgres-operator
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    version: ~1.10
    condition: postgres-operator.enabled
  - name: minio-operator
    repository: https://operator.min.io/
    version: ~4.3
    condition: minio-operator.enabled
  # Charts:
  - name: aacchart
    repository: "file://charts/aacchart"
    version: "0.1.0"
    condition: aacchart.enabled
  - name: fakesmtpchart
    repository: "file://charts/fakesmtpchart"
    version: "0.1.0"
    condition: fakesmtpchart.enabled
  - name: gamificationchart
    repository: "file://charts/gamificationchart"
    version: "0.1.0"
    condition: gamificationchart.enabled
  - name: miniochart
    repository: "file://charts/miniochart"
    version: "0.1.0"
    condition: miniochart.enabled
  - name: mongoDB
    repository: "file://charts/mongoDB"
    version: "0.1.0"
    condition: mongoDB.enabled
  - name: mysqlchart
    repository: "file://charts/mysqlchart"
    version: "0.1.0"
    condition: mysqlchart.enabled
  - name: playandgochart
    repository: "file://charts/playandgochart"
    version: "0.1.0"
    condition: playandgochart.enabled
  - name: rabbitchart
    repository: "file://charts/rabbitchart"
    version: "0.1.0"
    condition: rabbitchart.enabled
  
    
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"