{{- if not .Values.mongoAdminCredsCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-password
type: Opaque
stringData:
  password: {{ .Values.mongodbAdminSecret.password }}
{{- end }}
---
{{- if not .Values.mongoPlayngoCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-playngo-engine-password
type: Opaque
stringData:
  password: {{ .Values.mongodbPlaySecret.password }}
{{- end }}
---
{{- if not .Values.mongoGamificationCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-gamification-engine-password
type: Opaque
stringData:
  password: {{ .Values.mongodbGamiEngineSecret.password }}
{{- end }}
---
{{- if not .Values.mongoGamiHscCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-gamification-hsc-password
type: Opaque
stringData:
  password: {{ .Values.mongodbGamiHscSecret.password }}
{{- end }}
---
{{- if not .Values.mongoMetricCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-metrics-endpoint-creds
type: Opaque
stringData:
  password: {{ .Values.mongodbMetricSecret.password }}
  username: {{ .Values.mongodbMetricSecret.username }}
{{- end }}