apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.gamification.service }}
spec:
  selector:
    app: gamification
    tier: engine
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.global.gamification.port }}
    targetPort: {{ .Values.global.gamification.port }}