{{- if not .Values.rabbituserGe.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: rabbituser-ge
type: Opaque
data:
  username: {{ .Values.rabbitUser.rabbituserGeUsername | b64enc }}
  password: {{ .Values.rabbitUser.rabbituserGePwd | b64enc }}
{{- end }}
---
{{- if not .Values.users.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: users
type: Opaque
data:
  users.yml: {{ .Values.userData.data | b64enc }}
{{- end }}
---
{{- if not .Values.mongoAdmin.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mongoadmin
type: Opaque
data:
  mongoadmin-username: {{ .Values.mongoAdmin.mongoadminUsername | b64enc }}
  mongoadmin-pwd: {{ .Values.mongoAdmin.mongoadminPwd | b64enc }}
{{- end }}
---
{{- if not .Values.mongoAuthDb.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-authdb
type: Opaque
data:
  db: {{ .Values.mongoAuth.db | b64enc }}
{{- end }}