apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.fakeSmtp.service }}
spec:
  selector:
    app: {{ .Values.global.fakeSmtp.app }}
  ports:
    - protocol: {{ .Values.service.protocol1 }}
      name: {{ .Values.service.name1 }}
      port: {{ .Values.global.fakeSmtp.port }}
      targetPort: {{ .Values.global.fakeSmtp.port }}
    - protocol: {{ .Values.service.protocol2 }}
      name: {{ .Values.service.name2 }}
      port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.targetPort2 }}
    - protocol: {{ .Values.service.protocol3 }}
      name: {{ .Values.service.name3 }}
      port: {{ .Values.service.port3 }}
      targetPort: {{ .Values.service.targetPort3 }}