apiVersion: v1
kind: Service
metadata:
  name: playngo-engine
spec:
  selector:
    app: playngo
    tier: engine
  ports:
  - protocol: {{ .Values.service.portProtocol }}
    name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
