{{- if not .Values.creds.gamification.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: gamification
type: Opaque
data:
  gamification-username: {{ .Values.secrets.gamificationUsername | b64enc }}
  gamification-pwd: {{ .Values.secrets.gamificationPwd | b64enc }}
  gamification-sk1: {{ .Values.secrets.gamificationSk1 | b64enc }}
  gamification-sk2: {{ .Values.secrets.gamificationSk2 | b64enc }}
{{- end }}
---
{{- if not .Values.creds.rabbitUserPg.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: rabbituser-pg
type: Opaque
data:
  username: {{ .Values.secrets.rabbitUserPgUsername | b64enc }}
  password: {{ .Values.secrets.rabbitUserPgPwd | b64enc }}
{{- end }}
---
{{- if not .Values.creds.minio.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
data:
  minio-ak: {{ .Values.secrets.minioAk | b64enc }}
  minio-sk: {{ .Values.secrets.minioSk | b64enc }}
{{- end }}
---
{{- if not .Values.creds.aziende.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: aziende
type: Opaque
data:
  aziende-pwd: {{ .Values.secrets.aziendePwd | b64enc }}
  aziende-username: {{ .Values.secrets.aziendeUsername | b64enc }}
{{- end }}
---
{{- if not .Values.creds.gcmSender.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: gcm-sender
type: Opaque
data:
  gcm-sender-apikey: {{ .Values.secrets.gcmSenderApiKey | b64enc }}
  gcm-sender-id: {{ .Values.secrets.gcmSenderId | b64enc }}
{{- end }}