apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aac-ingress
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- if .Values.ingress.tlsEnabled }}
  tls:
  - hosts:
      - {{ .Values.ingress.tlsHost }}
    secretName: aac-tls-secret
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.global.aac.service }}
                port:
                  number: {{ .Values.global.aac.port }}