apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.aac.service }}
spec:
  selector:
    app: aac
    tier: aac
  ports:
  - protocol: TCP
    port: {{ .Values.global.aac.port }}
    targetPort: {{ .Values.global.aac.port }}