{{- if not .Values.mysqlCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
type: Opaque
data:
  mysql-user-pwd: {{ .Values.mysqlSecret.mysqlUserPwd | b64enc }}
  mysql-user-username: {{ .Values.mysqlSecret.mysqlUserUsername | b64enc }}
{{- end }}