{{- if not .Values.initMySqlCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mysqladmin
type: Opaque
data:
  mysqladmin-user-pwd: {{ .Values.mysqlAdminSecret.mysqladminPwd | b64enc }}
  mysqladmin-user-username: {{ .Values.mysqlAdminSecret.mysqladminUser | b64enc }}
{{- end }}