{{- if not .Values.fakeserverCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: smtp-user
type: Opaque
data:
  smtp-user-pwd: {{ .Values.fakeserverSecret.smtpUserPwd | b64enc }}
  smtp-user-username: {{ .Values.fakeserverSecret.smtpUserUsername | b64enc }}
{{- end }}